/*
 Navicat Premium Data Transfer

 Source Server         : course_bucket
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1521
 Source Schema         : COURSEBUCKET

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 12/06/2021 16:05:51
*/


-- ----------------------------
-- Table structure for ADMIN
-- ----------------------------
DROP TABLE "COURSEBUCKET"."ADMIN";
CREATE TABLE "COURSEBUCKET"."ADMIN" (
  "ID" VARCHAR2(50 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for CATEGORY
-- ----------------------------
DROP TABLE "COURSEBUCKET"."CATEGORY";
CREATE TABLE "COURSEBUCKET"."CATEGORY" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(50 BYTE) NOT NULL,
  "PARENT_ID" NUMBER,
  "PHOTO_ID" NUMBER,
  "ADMIN_ID" VARCHAR2(50 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for COUNTRY
-- ----------------------------
DROP TABLE "COURSEBUCKET"."COUNTRY";
CREATE TABLE "COURSEBUCKET"."COUNTRY" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(30 BYTE) NOT NULL,
  "ADMIN_ID" VARCHAR2(50 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for COURSE
-- ----------------------------
DROP TABLE "COURSEBUCKET"."COURSE";
CREATE TABLE "COURSEBUCKET"."COURSE" (
  "ID" NUMBER NOT NULL,
  "TITLE" VARCHAR2(200 BYTE),
  "SUBTITLE" VARCHAR2(200 BYTE),
  "DESCRIPTION" VARCHAR2(4000 BYTE),
  "PRICE" NUMBER,
  "OFFER" NUMBER,
  "PUBLISH_DATE" DATE,
  "IS_APPROVED" VARCHAR2(5 BYTE),
  "TEACHER_ID" VARCHAR2(50 BYTE),
  "COVER_ID" NUMBER,
  "CATEGORY_ID" NUMBER,
  "PREREQUISITES" VARCHAR2(4000 BYTE),
  "OUTCOMES" VARCHAR2(4000 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for COURSE_LANGUAGE
-- ----------------------------
DROP TABLE "COURSEBUCKET"."COURSE_LANGUAGE";
CREATE TABLE "COURSEBUCKET"."COURSE_LANGUAGE" (
  "ID" NUMBER NOT NULL,
  "COURSE_ID" NUMBER NOT NULL,
  "LANGUAGE_ID" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for COURSE_PROPERTIES
-- ----------------------------
DROP TABLE "COURSEBUCKET"."COURSE_PROPERTIES";
CREATE TABLE "COURSEBUCKET"."COURSE_PROPERTIES" (
  "ID" NUMBER NOT NULL,
  "ICON_ID" NUMBER,
  "COURSE_ID" NUMBER,
  "TEXT" VARCHAR2(4000 BYTE),
  "POSITION" NUMBER
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for CREDIT_CARD
-- ----------------------------
DROP TABLE "COURSEBUCKET"."CREDIT_CARD";
CREATE TABLE "COURSEBUCKET"."CREDIT_CARD" (
  "ID" NUMBER NOT NULL,
  "CARD_NO" NUMBER,
  "NAME_ON_CARD" VARCHAR2(50 BYTE),
  "EXPIRE_DATE" DATE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for DESIGNATION
-- ----------------------------
DROP TABLE "COURSEBUCKET"."DESIGNATION";
CREATE TABLE "COURSEBUCKET"."DESIGNATION" (
  "ID" NUMBER NOT NULL,
  "TYPE" VARCHAR2(50 BYTE) NOT NULL,
  "ADMIN_ID" VARCHAR2(50 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for EDUCATIONAL_STATUS
-- ----------------------------
DROP TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS";
CREATE TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" (
  "ID" NUMBER NOT NULL,
  "TYPE" VARCHAR2(50 BYTE) NOT NULL,
  "ADMIN_ID" VARCHAR2(50 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FAQ
-- ----------------------------
DROP TABLE "COURSEBUCKET"."FAQ";
CREATE TABLE "COURSEBUCKET"."FAQ" (
  "ID" NUMBER NOT NULL,
  "COURSE_ID" NUMBER NOT NULL,
  "STUDENT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "QUESTION" VARCHAR2(4000 BYTE) NOT NULL,
  "QUESTION_TIME" DATE NOT NULL,
  "ANSWER" VARCHAR2(4000 BYTE),
  "ANSWER_TIME" DATE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FILES
-- ----------------------------
DROP TABLE "COURSEBUCKET"."FILES";
CREATE TABLE "COURSEBUCKET"."FILES" (
  "ID" NUMBER NOT NULL,
  "TYPE" NUMBER NOT NULL,
  "TITLE" VARCHAR2(4000 BYTE),
  "CONTENT" VARCHAR2(4000 BYTE) NOT NULL,
  "UPLOAD_TIME" DATE NOT NULL,
  "LAST_UPDATE" DATE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FILE_TYPE
-- ----------------------------
DROP TABLE "COURSEBUCKET"."FILE_TYPE";
CREATE TABLE "COURSEBUCKET"."FILE_TYPE" (
  "ID" NUMBER NOT NULL,
  "TYPE" VARCHAR2(50 BYTE) NOT NULL,
  "ADMIN_ID" VARCHAR2(50 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for LANGUAGE
-- ----------------------------
DROP TABLE "COURSEBUCKET"."LANGUAGE";
CREATE TABLE "COURSEBUCKET"."LANGUAGE" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(50 BYTE) NOT NULL,
  "ADMIN_ID" VARCHAR2(50 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for LECTURE
-- ----------------------------
DROP TABLE "COURSEBUCKET"."LECTURE";
CREATE TABLE "COURSEBUCKET"."LECTURE" (
  "ID" NUMBER NOT NULL,
  "LECTURE_NO" NUMBER NOT NULL,
  "TITLE" VARCHAR2(200 BYTE) NOT NULL,
  "LAST_UPDATE" DATE NOT NULL,
  "IS_PREVIEW" CHAR(1 BYTE) NOT NULL,
  "WEEK_ID" NUMBER NOT NULL,
  "FILE_ID" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for MESSAGE
-- ----------------------------
DROP TABLE "COURSEBUCKET"."MESSAGE";
CREATE TABLE "COURSEBUCKET"."MESSAGE" (
  "ID" NUMBER NOT NULL,
  "SENDER_ID" VARCHAR2(50 BYTE) NOT NULL,
  "RECEIVER_ID" VARCHAR2(50 BYTE) NOT NULL,
  "FILE_ID" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for NOTIFICATION
-- ----------------------------
DROP TABLE "COURSEBUCKET"."NOTIFICATION";
CREATE TABLE "COURSEBUCKET"."NOTIFICATION" (
  "ID" NUMBER NOT NULL,
  "USER_ID" VARCHAR2(50 BYTE) NOT NULL,
  "FROM_ID" VARCHAR2(50 BYTE) NOT NULL,
  "TIME" DATE NOT NULL,
  "SEEN" VARCHAR2(5 BYTE) NOT NULL,
  "COURSE_ID" NUMBER,
  "TYPE" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PERSON
-- ----------------------------
DROP TABLE "COURSEBUCKET"."PERSON";
CREATE TABLE "COURSEBUCKET"."PERSON" (
  "ID" VARCHAR2(50 BYTE) NOT NULL,
  "EMAIL" VARCHAR2(200 BYTE) NOT NULL,
  "PASSWORD" VARCHAR2(200 BYTE) NOT NULL,
  "FIRST_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "LAST_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "DOB" DATE NOT NULL,
  "INSTITUTION" VARCHAR2(200 BYTE),
  "FB_URL" VARCHAR2(200 BYTE),
  "LINKEDIN_URL" VARCHAR2(200 BYTE),
  "SIGNUP_DATE" DATE NOT NULL,
  "ABOUT" VARCHAR2(4000 BYTE) NOT NULL,
  "COUNTRY_ID" NUMBER,
  "PHOTO_ID" NUMBER,
  "CARD_ID" NUMBER,
  "YOUTUBE_URL" VARCHAR2(200 BYTE),
  "WEBSITE" VARCHAR2(200 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PERSON_LANGUAGE
-- ----------------------------
DROP TABLE "COURSEBUCKET"."PERSON_LANGUAGE";
CREATE TABLE "COURSEBUCKET"."PERSON_LANGUAGE" (
  "ID" NUMBER NOT NULL,
  "PERSON_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LANGUAGE_ID" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PURCHASE_HISTORY
-- ----------------------------
DROP TABLE "COURSEBUCKET"."PURCHASE_HISTORY";
CREATE TABLE "COURSEBUCKET"."PURCHASE_HISTORY" (
  "ID" NUMBER NOT NULL,
  "COURSE_ID" NUMBER NOT NULL,
  "STUDENT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "TIME" DATE NOT NULL,
  "COST" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for RATING
-- ----------------------------
DROP TABLE "COURSEBUCKET"."RATING";
CREATE TABLE "COURSEBUCKET"."RATING" (
  "ID" NUMBER NOT NULL,
  "COURSE_ID" NUMBER NOT NULL,
  "STUDENT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "VALUE" NUMBER NOT NULL,
  "TIME" DATE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for REVIEW
-- ----------------------------
DROP TABLE "COURSEBUCKET"."REVIEW";
CREATE TABLE "COURSEBUCKET"."REVIEW" (
  "ID" NUMBER NOT NULL,
  "COURSE_ID" NUMBER NOT NULL,
  "STUDENT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "TIME" DATE NOT NULL,
  "TEXT" VARCHAR2(4000 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STUDENT
-- ----------------------------
DROP TABLE "COURSEBUCKET"."STUDENT";
CREATE TABLE "COURSEBUCKET"."STUDENT" (
  "ID" VARCHAR2(50 BYTE) NOT NULL,
  "EDU_STATUS_ID" NUMBER
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for TEACHER
-- ----------------------------
DROP TABLE "COURSEBUCKET"."TEACHER";
CREATE TABLE "COURSEBUCKET"."TEACHER" (
  "ID" VARCHAR2(50 BYTE) NOT NULL,
  "DESIGNATION_ID" NUMBER
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for WEEK
-- ----------------------------
DROP TABLE "COURSEBUCKET"."WEEK";
CREATE TABLE "COURSEBUCKET"."WEEK" (
  "ID" NUMBER NOT NULL,
  "WEEK_NO" NUMBER NOT NULL,
  "TITLE" VARCHAR2(200 BYTE) NOT NULL,
  "LAST_UPDATE" DATE NOT NULL,
  "COURSE_ID" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Function structure for ERASE_NOTIFICATION
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "COURSEBUCKET"."ERASE_NOTIFICATION" AS
BEGIN
	FOR it IN (SELECT ID from NOTIFICATION WHERE USER_ID = userid ORDER BY TIME DESC) LOOP
        IF r > n THEN
            DELETE FROM NOTIFICATION WHERE ID = it.ID ;
        END IF;
        r := r+1;
	END LOOP;

EXCEPTION
    WHEN no_data_found THEN
        dbms_output.put_line('invalid employee id');
    WHEN others THEN
        dbms_output.put_line('unknown error' );

END;
/

-- ----------------------------
-- Function structure for GET_RATING
-- ----------------------------
CREATE OR REPLACE
FUNCTION "COURSEBUCKET"."GET_RATING" AS
BEGIN
	RATING_VALUE := 0;
	COUNTT := 0;
	FOR C IN (
						SELECT AVG(R.VALUE) AVG_VALUE 
						FROM RATING R 
						WHERE COURSE_ID = ID_COURSE
					 )
	LOOP
		RATING_VALUE := RATING_VALUE + NVL(C.AVG_VALUE,0);
		COUNTT := COUNTT + 1;
	END LOOP;

	RATING_VALUE := RATING_VALUE/COUNTT;
	RETURN RATING_VALUE;
END;
/

-- ----------------------------
-- Function structure for GET_REVIEW
-- ----------------------------
CREATE OR REPLACE
FUNCTION "COURSEBUCKET"."GET_REVIEW" AS
BEGIN
	REVIEW_VALUE := 0;
	FOR C IN (
						SELECT COURSE_ID
						FROM REVIEW R 
						WHERE COURSE_ID = ID_COURSE
					 )
	LOOP
		REVIEW_VALUE := REVIEW_VALUE + 1;
	END LOOP;
	RETURN REVIEW_VALUE;
END;
/

-- ----------------------------
-- Function structure for NUM_OF_STUDENT
-- ----------------------------
CREATE OR REPLACE
FUNCTION "COURSEBUCKET"."NUM_OF_STUDENT" AS
BEGIN
	NUM := 0;
	FOR C IN (
						SELECT ID
						FROM PURCHASE_HISTORY 
						WHERE COURSE_ID = ID_COURSE
					 )
	LOOP
		NUM := NUM + 1;
	END LOOP;
	RETURN NUM;
END;
/

-- ----------------------------
-- Sequence structure for AUTO_ID
-- ----------------------------
DROP SEQUENCE "COURSEBUCKET"."AUTO_ID";
CREATE SEQUENCE "COURSEBUCKET"."AUTO_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for AUTO_ID1
-- ----------------------------
DROP SEQUENCE "COURSEBUCKET"."AUTO_ID1";
CREATE SEQUENCE "COURSEBUCKET"."AUTO_ID1" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for NOTIFICATION_ID
-- ----------------------------
DROP SEQUENCE "COURSEBUCKET"."NOTIFICATION_ID";
CREATE SEQUENCE "COURSEBUCKET"."NOTIFICATION_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for id
-- ----------------------------
DROP SEQUENCE "COURSEBUCKET"."id";
CREATE SEQUENCE "COURSEBUCKET"."id" MINVALUE 1 MAXVALUE 1000000 INCREMENT BY 1 ORDER CACHE 10;

-- ----------------------------
-- Primary Key structure for table ADMIN
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ADMIN
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."ADMIN" ADD CONSTRAINT "SYS_C0013282" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."ADMIN" ADD CONSTRAINT "SYS_C0014467" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."ADMIN" ADD CONSTRAINT "SYS_C0014675" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."ADMIN" ADD CONSTRAINT "SYS_C0015484" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."ADMIN" ADD CONSTRAINT "SYS_C0019279" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CATEGORY
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table CATEGORY
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0019747" UNIQUE ("NAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table CATEGORY
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0013284" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0013285" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0013287" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0014468" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0014469" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0014470" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0014676" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0014677" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0014678" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0015491" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0015492" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0015493" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0019291" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0019292" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "SYS_C0019293" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table COUNTRY
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table COUNTRY
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0013289" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0013290" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0013291" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0014471" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0014472" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0014473" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0014679" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0014680" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0014681" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0015504" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0015505" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0015506" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0019307" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0019308" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "SYS_C0019309" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table COURSE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table COURSE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."COURSE" ADD CONSTRAINT "SYS_C0013293" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE" ADD CONSTRAINT "SYS_C0014474" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE" ADD CONSTRAINT "SYS_C0014682" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE" ADD CONSTRAINT "SYS_C0015515" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE" ADD CONSTRAINT "SYS_C0019317" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table COURSE
-- ----------------------------
CREATE TRIGGER "COURSEBUCKET"."COURSE_DELETE" BEFORE DELETE ON "COURSEBUCKET"."COURSE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
	DELETE FROM COURSE_LANGUAGE WHERE COURSE_ID = :OLD.ID;
	DELETE FROM COURSE_PROPERTIES WHERE COURSE_ID = :OLD.ID;
	DELETE FROM WEEK WHERE COURSE_ID = :OLD.ID;
	DELETE FROM REVIEW WHERE COURSE_ID = :OLD.ID;
	DELETE FROM RATING WHERE COURSE_ID = :OLD.ID;
	DBMS_OUTPUT.put_line('Ok');
END;
/

-- ----------------------------
-- Primary Key structure for table COURSE_LANGUAGE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "COURSE_LANGUAGE_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table COURSE_LANGUAGE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0013304" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0013305" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0013306" CHECK ("LANGUAGE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0014475" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0014476" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0014477" CHECK ("LANGUAGE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0014683" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0014684" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0014685" CHECK ("LANGUAGE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0015528" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0015529" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0015530" CHECK ("LANGUAGE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0019329" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0019330" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "SYS_C0019331" CHECK ("LANGUAGE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table COURSE_PROPERTIES
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."COURSE_PROPERTIES" ADD CONSTRAINT "COURSE_OUTCOME_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table COURSE_PROPERTIES
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."COURSE_PROPERTIES" ADD CONSTRAINT "SYS_C0013308" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_PROPERTIES" ADD CONSTRAINT "SYS_C0014478" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_PROPERTIES" ADD CONSTRAINT "SYS_C0014686" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_PROPERTIES" ADD CONSTRAINT "SYS_C0015535" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_PROPERTIES" ADD CONSTRAINT "SYS_C0019339" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CREDIT_CARD
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."CREDIT_CARD" ADD CONSTRAINT "CREDIT_CARD_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CREDIT_CARD
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."CREDIT_CARD" ADD CONSTRAINT "SYS_C0013316" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CREDIT_CARD" ADD CONSTRAINT "SYS_C0014479" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CREDIT_CARD" ADD CONSTRAINT "SYS_C0014687" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CREDIT_CARD" ADD CONSTRAINT "SYS_C0015538" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CREDIT_CARD" ADD CONSTRAINT "SYS_C0019345" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DESIGNATION
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "DESIGNATION_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table DESIGNATION
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0013318" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0013319" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0013320" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0014480" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0014481" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0014482" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0014688" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0014689" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0014690" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0015545" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0015546" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0015547" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0019357" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0019358" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "SYS_C0019359" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDUCATIONAL_STATUS
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "EDUCATIONAL_STATUS_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EDUCATIONAL_STATUS
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0013322" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0013323" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0013324" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0014483" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0014484" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0014485" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0014691" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0014692" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0014693" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0015558" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0015559" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0015560" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0019373" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0019374" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "SYS_C0019375" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table FAQ
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "FAQ_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table FAQ
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0013326" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0013327" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0013328" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0013329" CHECK ("QUESTION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0013330" CHECK ("QUESTION_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0014486" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0014487" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0014488" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0014489" CHECK ("QUESTION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0014490" CHECK ("QUESTION_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0014694" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0014695" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0014696" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0014697" CHECK ("QUESTION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0014698" CHECK ("QUESTION_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0015583" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0015584" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0015585" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0015586" CHECK ("QUESTION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0015587" CHECK ("QUESTION_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0019395" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0019396" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0019397" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0019398" CHECK ("QUESTION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "SYS_C0019399" CHECK ("QUESTION_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table FILES
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table FILES
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0013336" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0013337" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0013339" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0013340" CHECK ("UPLOAD_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0013341" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0014491" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0014492" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0014493" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0014494" CHECK ("UPLOAD_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0014495" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0014699" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0014700" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0014701" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0014702" CHECK ("UPLOAD_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0014703" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0015593" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0015594" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0015595" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0015596" CHECK ("UPLOAD_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0015597" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0019420" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0019421" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0019422" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0019423" CHECK ("UPLOAD_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "SYS_C0019424" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table FILE_TYPE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "FILE_TYPE_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table FILE_TYPE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0013332" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0013333" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0013334" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0014496" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0014497" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0014498" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0014704" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0014705" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0014706" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0015613" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0015614" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0015615" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0019441" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0019442" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "SYS_C0019443" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table LANGUAGE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "LANGUAGE_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table LANGUAGE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0013345" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0013346" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0013347" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0014499" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0014500" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0014501" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0014707" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0014708" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0014709" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0015626" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0015627" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0015628" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0019457" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0019458" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "SYS_C0019459" CHECK ("ADMIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table LECTURE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "LECTURE_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table LECTURE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0013349" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0013350" CHECK ("LECTURE_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0013351" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0013352" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0013353" CHECK ("IS_PREVIEW" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0013354" CHECK ("WEEK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0013970" CHECK ("FILE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014502" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014503" CHECK ("LECTURE_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014504" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014505" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014506" CHECK ("IS_PREVIEW" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014507" CHECK ("WEEK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014508" CHECK ("FILE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014710" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014711" CHECK ("LECTURE_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014712" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014713" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014714" CHECK ("IS_PREVIEW" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014715" CHECK ("WEEK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0014716" CHECK ("FILE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0015657" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0015658" CHECK ("LECTURE_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0015659" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0015660" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0015661" CHECK ("IS_PREVIEW" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0015662" CHECK ("WEEK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0015663" CHECK ("FILE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0019485" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0019486" CHECK ("LECTURE_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0019487" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0019488" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0019489" CHECK ("IS_PREVIEW" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0019490" CHECK ("WEEK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "SYS_C0019491" CHECK ("FILE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table MESSAGE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."MESSAGE" ADD CONSTRAINT "SYS_C0015888" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table MESSAGE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."MESSAGE" ADD CONSTRAINT "SYS_C0015886" CHECK ("SENDER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."MESSAGE" ADD CONSTRAINT "SYS_C0015887" CHECK ("RECEIVER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."MESSAGE" ADD CONSTRAINT "SYS_C0015891" CHECK ("FILE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."MESSAGE" ADD CONSTRAINT "SYS_C0019499" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."MESSAGE" ADD CONSTRAINT "SYS_C0019500" CHECK ("SENDER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."MESSAGE" ADD CONSTRAINT "SYS_C0019501" CHECK ("RECEIVER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."MESSAGE" ADD CONSTRAINT "SYS_C0019502" CHECK ("FILE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table NOTIFICATION
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table NOTIFICATION
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."NOTIFICATION" ADD CONSTRAINT "SYS_C0019508" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."NOTIFICATION" ADD CONSTRAINT "SYS_C0019509" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."NOTIFICATION" ADD CONSTRAINT "SYS_C0019510" CHECK ("FROM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."NOTIFICATION" ADD CONSTRAINT "SYS_C0019511" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."NOTIFICATION" ADD CONSTRAINT "SYS_C0019512" CHECK ("SEEN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table NOTIFICATION
-- ----------------------------
CREATE TRIGGER "COURSEBUCKET"."NTFCN_AUTO_DELETE" BEFORE INSERT ON "COURSEBUCKET"."NOTIFICATION" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
  ERASE_NOTIFICATION(10,:new.USER_ID);
END;
/
CREATE TRIGGER "COURSEBUCKET"."NTFCN_AUTO_ID" BEFORE INSERT ON "COURSEBUCKET"."NOTIFICATION" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
  :new.ID := NOTIFICATION_ID.nextval;
END;
/

-- ----------------------------
-- Primary Key structure for table PERSON
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table PERSON
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0019814" UNIQUE ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table PERSON
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0013356" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0013357" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0013358" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0013359" CHECK ("FIRST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0013360" CHECK ("LAST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0013361" CHECK ("SIGNUP_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0013362" CHECK ("ABOUT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0013732" CHECK ("DOB" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014509" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014510" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014511" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014512" CHECK ("FIRST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014513" CHECK ("LAST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014514" CHECK ("DOB" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014515" CHECK ("SIGNUP_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014516" CHECK ("ABOUT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014717" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014718" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014719" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014720" CHECK ("FIRST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014721" CHECK ("LAST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014722" CHECK ("DOB" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014723" CHECK ("SIGNUP_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0014724" CHECK ("ABOUT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0015673" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0015674" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0015675" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0015676" CHECK ("FIRST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0015677" CHECK ("LAST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0015678" CHECK ("DOB" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0015679" CHECK ("SIGNUP_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0015680" CHECK ("ABOUT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0019538" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0019539" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0019540" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0019541" CHECK ("FIRST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0019542" CHECK ("LAST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0019543" CHECK ("DOB" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0019544" CHECK ("SIGNUP_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "SYS_C0019545" CHECK ("ABOUT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PERSON_LANGUAGE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "PERSON_LANGUAGE_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PERSON_LANGUAGE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0013364" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0013365" CHECK ("PERSON_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0013366" CHECK ("LANGUAGE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0014517" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0014518" CHECK ("PERSON_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0014519" CHECK ("LANGUAGE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0014725" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0014726" CHECK ("PERSON_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0014727" CHECK ("LANGUAGE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0015707" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0015708" CHECK ("PERSON_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0015709" CHECK ("LANGUAGE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0019564" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0019565" CHECK ("PERSON_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "SYS_C0019566" CHECK ("LANGUAGE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PURCHASE_HISTORY
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "PURCHASE_HISTORY_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PURCHASE_HISTORY
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0013368" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0013369" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0013370" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0013371" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0013372" CHECK ("COST" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0014520" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0014521" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0014522" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0014523" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0014524" CHECK ("COST" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0014728" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0014729" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0014730" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0014731" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0014732" CHECK ("COST" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0015726" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0015727" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0015728" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0015729" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0015730" CHECK ("COST" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0019586" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0019587" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0019588" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0019589" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "SYS_C0019590" CHECK ("COST" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table RATING
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "RATING_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RATING
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0013374" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0013375" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0013376" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0013377" CHECK ("VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0013378" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0014525" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0014526" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0014527" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0014528" CHECK ("VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0014529" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0014733" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0014734" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0014735" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0014736" CHECK ("VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0014737" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0015747" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0015748" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0015749" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0015750" CHECK ("VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0015751" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0019612" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0019613" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0019614" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0019615" CHECK ("VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "SYS_C0019616" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table REVIEW
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "REVIEW_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table REVIEW
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0013380" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0013381" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0013382" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0013383" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0013384" CHECK ("TEXT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0014530" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0014531" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0014532" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0014533" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0014534" CHECK ("TEXT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0014738" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0014739" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0014740" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0014741" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0014742" CHECK ("TEXT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0015768" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0015769" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0015770" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0015771" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0015772" CHECK ("TEXT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0019638" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0019639" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0019640" CHECK ("STUDENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0019641" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "SYS_C0019642" CHECK ("TEXT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table STUDENT
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table STUDENT
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."STUDENT" ADD CONSTRAINT "SYS_C0013386" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."STUDENT" ADD CONSTRAINT "SYS_C0014537" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."STUDENT" ADD CONSTRAINT "SYS_C0014745" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."STUDENT" ADD CONSTRAINT "SYS_C0015785" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."STUDENT" ADD CONSTRAINT "SYS_C0019652" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TEACHER
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."TEACHER" ADD CONSTRAINT "INSTRUCTOR_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TEACHER
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."TEACHER" ADD CONSTRAINT "SYS_C0013343" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."TEACHER" ADD CONSTRAINT "SYS_C0014538" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."TEACHER" ADD CONSTRAINT "SYS_C0014746" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."TEACHER" ADD CONSTRAINT "SYS_C0015789" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."TEACHER" ADD CONSTRAINT "SYS_C0019658" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table WEEK
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "WEEK_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table WEEK
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0013388" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0013389" CHECK ("WEEK_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0013390" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0013391" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0013392" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0014539" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0014540" CHECK ("WEEK_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0014541" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0014542" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0014543" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0014747" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0014748" CHECK ("WEEK_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0014749" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0014750" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0014751" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0015802" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0015803" CHECK ("WEEK_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0015804" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0015805" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0015806" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0019675" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0019676" CHECK ("WEEK_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0019677" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0019678" CHECK ("LAST_UPDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "SYS_C0019679" CHECK ("COURSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table WEEK
-- ----------------------------
CREATE TRIGGER "COURSEBUCKET"."WEEK_DELETE" BEFORE DELETE ON "COURSEBUCKET"."WEEK" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
	DELETE FROM LECTURE WHERE WEEK_ID = :OLD.ID;
	DBMS_OUTPUT.put_line('Ok');
END;
/

-- ----------------------------
-- Foreign Keys structure for table CATEGORY
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "CATEGORY_SUB_CATEGORY" FOREIGN KEY ("PARENT_ID") REFERENCES "COURSEBUCKET"."CATEGORY" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."CATEGORY" ADD CONSTRAINT "CAT_AD" FOREIGN KEY ("ADMIN_ID") REFERENCES "COURSEBUCKET"."ADMIN" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table COUNTRY
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."COUNTRY" ADD CONSTRAINT "CON_AD" FOREIGN KEY ("ADMIN_ID") REFERENCES "COURSEBUCKET"."ADMIN" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table COURSE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."COURSE" ADD CONSTRAINT "COURSE_CATEGORY" FOREIGN KEY ("CATEGORY_ID") REFERENCES "COURSEBUCKET"."CATEGORY" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE" ADD CONSTRAINT "COURSE_COVER" FOREIGN KEY ("COVER_ID") REFERENCES "COURSEBUCKET"."FILES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE" ADD CONSTRAINT "COURSE_INSTRUCTOR" FOREIGN KEY ("TEACHER_ID") REFERENCES "COURSEBUCKET"."TEACHER" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table COURSE_LANGUAGE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "COURSE_LANGUAGE" FOREIGN KEY ("COURSE_ID") REFERENCES "COURSEBUCKET"."COURSE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."COURSE_LANGUAGE" ADD CONSTRAINT "COURSE_LANG_ID" FOREIGN KEY ("LANGUAGE_ID") REFERENCES "COURSEBUCKET"."LANGUAGE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table COURSE_PROPERTIES
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."COURSE_PROPERTIES" ADD CONSTRAINT "COURSE_OUTCOME_ID" FOREIGN KEY ("COURSE_ID") REFERENCES "COURSEBUCKET"."COURSE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table DESIGNATION
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."DESIGNATION" ADD CONSTRAINT "DES_AD" FOREIGN KEY ("ADMIN_ID") REFERENCES "COURSEBUCKET"."ADMIN" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table EDUCATIONAL_STATUS
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."EDUCATIONAL_STATUS" ADD CONSTRAINT "EDU_AD" FOREIGN KEY ("ADMIN_ID") REFERENCES "COURSEBUCKET"."ADMIN" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table FAQ
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "FCI" FOREIGN KEY ("COURSE_ID") REFERENCES "COURSEBUCKET"."COURSE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."FAQ" ADD CONSTRAINT "FSI" FOREIGN KEY ("STUDENT_ID") REFERENCES "COURSEBUCKET"."STUDENT" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table FILES
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."FILES" ADD CONSTRAINT "FIL_KE" FOREIGN KEY ("TYPE") REFERENCES "COURSEBUCKET"."FILE_TYPE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table FILE_TYPE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."FILE_TYPE" ADD CONSTRAINT "FILE_AD" FOREIGN KEY ("ADMIN_ID") REFERENCES "COURSEBUCKET"."ADMIN" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table LANGUAGE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."LANGUAGE" ADD CONSTRAINT "LANG_AD" FOREIGN KEY ("ADMIN_ID") REFERENCES "COURSEBUCKET"."ADMIN" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table LECTURE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."LECTURE" ADD CONSTRAINT "LECTURE_WEEK" FOREIGN KEY ("WEEK_ID") REFERENCES "COURSEBUCKET"."WEEK" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table MESSAGE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."MESSAGE" ADD CONSTRAINT "MESSAGE_CONTENT" FOREIGN KEY ("FILE_ID") REFERENCES "COURSEBUCKET"."FILES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."MESSAGE" ADD CONSTRAINT "MESSAGE_RECEIVER" FOREIGN KEY ("RECEIVER_ID") REFERENCES "COURSEBUCKET"."PERSON" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."MESSAGE" ADD CONSTRAINT "MESSAGE_SENDER" FOREIGN KEY ("SENDER_ID") REFERENCES "COURSEBUCKET"."PERSON" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table NOTIFICATION
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."NOTIFICATION" ADD CONSTRAINT "PER_NOT" FOREIGN KEY ("USER_ID") REFERENCES "COURSEBUCKET"."PERSON" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PERSON
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "PER_CAR" FOREIGN KEY ("CARD_ID") REFERENCES "COURSEBUCKET"."CREDIT_CARD" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "PER_CON" FOREIGN KEY ("COUNTRY_ID") REFERENCES "COURSEBUCKET"."COUNTRY" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON" ADD CONSTRAINT "PER_PHO" FOREIGN KEY ("PHOTO_ID") REFERENCES "COURSEBUCKET"."FILES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PERSON_LANGUAGE
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "PER_LANG_LANG" FOREIGN KEY ("LANGUAGE_ID") REFERENCES "COURSEBUCKET"."LANGUAGE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PERSON_LANGUAGE" ADD CONSTRAINT "PER_LANG_PER" FOREIGN KEY ("PERSON_ID") REFERENCES "COURSEBUCKET"."PERSON" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PURCHASE_HISTORY
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "PUR_COUR" FOREIGN KEY ("COURSE_ID") REFERENCES "COURSEBUCKET"."COURSE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."PURCHASE_HISTORY" ADD CONSTRAINT "PUR_STU" FOREIGN KEY ("STUDENT_ID") REFERENCES "COURSEBUCKET"."STUDENT" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table RATING
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "RAT_COUR" FOREIGN KEY ("COURSE_ID") REFERENCES "COURSEBUCKET"."COURSE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."RATING" ADD CONSTRAINT "RAT_STU" FOREIGN KEY ("STUDENT_ID") REFERENCES "COURSEBUCKET"."STUDENT" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table REVIEW
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "REV_COUR" FOREIGN KEY ("COURSE_ID") REFERENCES "COURSEBUCKET"."COURSE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "COURSEBUCKET"."REVIEW" ADD CONSTRAINT "REV_STU" FOREIGN KEY ("STUDENT_ID") REFERENCES "COURSEBUCKET"."STUDENT" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table STUDENT
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."STUDENT" ADD CONSTRAINT "STU_EDU" FOREIGN KEY ("EDU_STATUS_ID") REFERENCES "COURSEBUCKET"."EDUCATIONAL_STATUS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table TEACHER
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."TEACHER" ADD CONSTRAINT "INST_DESIG" FOREIGN KEY ("DESIGNATION_ID") REFERENCES "COURSEBUCKET"."DESIGNATION" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table WEEK
-- ----------------------------
ALTER TABLE "COURSEBUCKET"."WEEK" ADD CONSTRAINT "WEEK_COURSE" FOREIGN KEY ("COURSE_ID") REFERENCES "COURSEBUCKET"."COURSE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
